---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - pods
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - clustermanagementaddons
  - managedclusteraddons
  - managedclusteraddons/finalizers
  - managedclusteraddons/status
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
  - get
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  - certificatesigningrequests/approval
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - signers
  verbs:
  - approve
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - console.openshift.io
  resources:
  - consoleplugins
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - multicluster.odf.openshift.io
  resources:
  - mirrorpeers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multicluster.odf.openshift.io
  resources:
  - mirrorpeers/finalizers
  verbs:
  - update
- apiGroups:
  - multicluster.odf.openshift.io
  resources:
  - mirrorpeers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ramendr.openshift.io
  resources:
  - drclusters
  - drpolicies
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - spoke-clusterrole-bindings
  resources:
  - clusterrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - '*'
- apiGroups:
  - view.open-cluster-management.io
  resources:
  - managedclusterviews
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - work.open-cluster-management.io
  resources:
  - manifestworks
  verbs:
  - '*'
